version: "3.9"

services:
  flask-app:
    build: .
    container_name: flask_socketio_chat
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
